export const matches: {
    homeTeamId: string
    awayTeamId: string
    score: string
    week: number
    type: string
    date: string
    time: string
    venue: string
    events: MatchEvent[]
}[] = [

        //week1
        {
            homeTeamId: "azul",
            awayTeamId: "blacklabel",
            score: "2 : 2",
            week: 1,
            type: "league",
            date: "2025-07-31",
            time: "20:00",
            venue: "Lapangan B",
            events: [
                { type: "goal", team: "home", player: "jono", minute: 20, assist: "cibex" },
                { type: "goal", team: "home", player: "cibex", minute: 23, assist: "jono" },
                { type: "yellow", team: "home", player: "ricky", minute: 45 },
                { type: "goal", team: "away", player: "titus", minute: 3, assist: "swan" },
                { type: "goal", team: "away", player: "titus", minute: 12, assist: "zhongyen" },
                { type: "yellow", team: "away", player: "willy", minute: 37 },
            ] as unknown as MatchEvent[],
        },
        {
            homeTeamId: "hennessy",
            awayTeamId: "cockburn",
            score: "1 : 1",
            week: 1,
            type: "league",
            date: "2025-07-31",
            time: "20:00",
            venue: "Lapangan C",
            events: [
                { type: "goal", team: "home", player: "wong (OG)", minute: 15 },
                { type: "yellow", team: "home", player: "yongsun", minute: 34 },
                { type: "goal", team: "away", player: "nino", minute: 30, assist: "kibuk" },
            ] as unknown as MatchEvent[],
        },
        {
            homeTeamId: "macallan",
            awayTeamId: "singleton",
            score: "3 : 2",
            week: 1,
            type: "league",
            date: "2025-07-31",
            time: "21:00",
            venue: "Lapangan B",
            events: [
                { type: "goal", team: "home", player: "daniel", minute: 3 },
                { type: "goal", team: "home", player: "bambang", minute: 31 },
                { type: "goal", team: "home", player: "budju", minute: 46, assist: "herwin" },
                { type: "goal", team: "away", player: "mitra", minute: 12, assist: "rbonn" },
                { type: "goal", team: "away", player: "acai", minute: 18, assist: "gabriel" },
            ] as unknown as MatchEvent[],
        },
        {
            homeTeamId: "hibiki",
            awayTeamId: "glenfiddich",
            score: "1 : 2",
            week: 1,
            type: "league",
            date: "2025-07-31",
            time: "21:00",
            venue: "Lapangan C",
            events: [
                { type: "goal", team: "home", player: "fauzi", minute: 44, assist: "riko" },
                { type: "goal", team: "away", player: "bayu", minute: 22, assist: "tony" },
                { type: "goal", team: "away", player: "bayu", minute: 47, assist: "tony" },
            ] as unknown as MatchEvent[],
        },

        //week2
        {
            homeTeamId: "macallan",
            awayTeamId: "cockburn",
            score: "1 : 3",
            week: 2,
            type: "league",
            date: "2025-08-7",
            time: "20:00",
            venue: "Lapangan B",
            events: [
                { type: "goal", team: "away", player: "rabin", minute: 17 },
                { type: "goal", team: "away", player: "nino", minute: 43, assist: "doni" },
                { type: "goal", team: "away", player: "nino", minute: 45 },
                { type: "goal", team: "home", player: "chandri", minute: 35, assist: "raynaldo" },
                { type: "yellow", team: "home", player: "daniel", minute: 39 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "hibiki",
            awayTeamId: "azul",
            score: "5 : 2",
            week: 2,
            type: "league",
            date: "2025-08-7",
            time: "20:00",
            venue: "Lapangan C",
            events: [
                { type: "goal", team: "away", player: "cibex", minute: 21, assist: "winsen" },
                { type: "goal", team: "away", player: "jono", minute: 35 },
                { type: "yellow", team: "away", player: "ricky", minute: 22 },
                { type: "goal", team: "home", player: "riko", minute: 5 },
                { type: "goal", team: "home", player: "ricky (OG)", minute: 12 },
                { type: "goal", team: "home", player: "ayang", minute: 15 },
                { type: "goal", team: "home", player: "manhoi", minute: 31, assist: "fauzi" },
                { type: "goal", team: "home", player: "fauzi", minute: 46 },
                { type: "yellow", team: "home", player: "fico", minute: 45 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "blacklabel",
            awayTeamId: "glenfiddich",
            score: "5 : 2",
            week: 2,
            type: "league",
            date: "2025-08-7",
            time: "21:00",
            venue: "Lapangan B",
            events: [
                { type: "goal", team: "away", player: "bayu", minute: 6, assist: "akok" },
                { type: "goal", team: "away", player: "tony", minute: 44 },
                { type: "yellow", team: "away", player: "desmond", minute: 17 },
                { type: "goal", team: "home", player: "swan", minute: 5, assist: "ferry" },
                { type: "goal", team: "home", player: "titus", minute: 29, assist: "johanbutet" },
                { type: "goal", team: "home", player: "podiman", minute: 31 },
                { type: "goal", team: "home", player: "titus", minute: 35, assist: "podiman" },
                { type: "goal", team: "home", player: "podiman", minute: 44 },
                { type: "yellow", team: "home", player: "ferry", minute: 32 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "hennessy",
            awayTeamId: "singleton",
            score: "2 : 4",
            week: 2,
            type: "league",
            date: "2025-08-7",
            time: "21:00",
            venue: "Lapangan C",
            events: [
                { type: "goal", team: "away", player: "acent", minute: 12, assist: "kelvin" },
                { type: "goal", team: "away", player: "wewek (OG)", minute: 14 },
                { type: "goal", team: "away", player: "auco", minute: 22, assist: "kelvin" },
                { type: "goal", team: "away", player: "auco", minute: 29, assist: "kelvin" },
                { type: "goal", team: "home", player: "awen", minute: 31 },
                { type: "goal", team: "home", player: "salja", minute: 44 },
            ] as MatchEvent[],
        },

        //cup1
        {
            homeTeamId: "blacklabel",
            awayTeamId: "hibiki",
            score: "0 : 1",
            week: 1,
            type: "cup",
            date: "2025-08-14",
            time: "20:00",
            venue: "Lapangan B",
            events: [
                { type: "goal", team: "away", player: "ayang", minute: 18, assist: "vj" },
                { type: "yellow", team: "away", player: "riko", minute: 46 },
                { type: "yellow", team: "away", player: "fico", minute: 44 },
                { type: "yellow", team: "home", player: "ferry", minute: 36 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "glenfiddich",
            awayTeamId: "azul",
            score: "1 : 2",
            week: 1,
            type: "cup",
            date: "2025-08-14",
            time: "20:00",
            venue: "Lapangan C",
            events: [
                { type: "goal", team: "away", player: "winsen", minute: 4 },
                { type: "goal", team: "away", player: "winsen", minute: 33, assist: "fahrun" },
                { type: "yellow", team: "away", player: "jono", minute: 24 },
                { type: "goal", team: "home", player: "yanssen", minute: 17, assist: "tony" },
                { type: "yellow", team: "home", player: "desmond", minute: 16 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "macallan",
            awayTeamId: "hennessy",
            score: "2 : 2",
            week: 1,
            type: "cup",
            date: "2025-08-14",
            time: "21:00",
            venue: "Lapangan B",
            events: [
                { type: "goal", team: "away", player: "wewek", minute: 4 },
                { type: "goal", team: "away", player: "awai", minute: 20 },
                { type: "goal", team: "home", player: "chandri", minute: 24, assist: "raynaldo" },
                { type: "goal", team: "home", player: "henry", minute: 36, assist: "daniel" },
                { type: "yellow", team: "home", player: "arifin", minute: 32 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "singleton",
            awayTeamId: "cockburn",
            score: "5 : 2",
            week: 1,
            type: "cup",
            date: "2025-08-14",
            time: "21:00",
            venue: "Lapangan C",
            events: [
                { type: "goal", team: "away", player: "doni", minute: 9 },
                { type: "goal", team: "away", player: "nino", minute: 17, assist: "james" },
                { type: "goal", team: "home", player: "rbonn", minute: 19 },
                { type: "goal", team: "home", player: "acent", minute: 27, assist: "mitra" },
                { type: "goal", team: "home", player: "auco", minute: 34, assist: "kelvin" },
                { type: "goal", team: "home", player: "vincent (OG)", minute: 44 },
                { type: "goal", team: "home", player: "mitra", minute: 48, assist: "auco" },
            ] as MatchEvent[],
        },

        //week3
        {
            homeTeamId: "singleton",
            awayTeamId: "hibiki",
            score: "3 : 5",
            week: 3,
            type: "league",
            date: "2025-08-21",
            time: "20:00",
            venue: "Lapangan B",
            events: [
                { type: "goal", team: "away", player: "fauzi", minute: 15 },
                { type: "goal", team: "away", player: "fauzi", minute: 18 },
                { type: "goal", team: "away", player: "fico", minute: 25, assist: "riko" },
                { type: "goal", team: "away", player: "fauzi", minute: 34, assist: "manhoi" },
                { type: "goal", team: "away", player: "manhoi", minute: 48 },
                { type: "yellow", team: "away", player: "delvin", minute: 15 },

                { type: "goal", team: "home", player: "kelvin", minute: 11 },
                { type: "goal", team: "home", player: "acent", minute: 12, assist: "mitra" },
                { type: "goal", team: "home", player: "auco", minute: 15 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "cockburn",
            awayTeamId: "blacklabel",
            score: "2 : 3",
            week: 3,
            type: "league",
            date: "2025-08-21",
            time: "20:00",
            venue: "Lapangan C",
            events: [
                { type: "goal", team: "away", player: "swan", minute: 22, assist: "bobby" },
                { type: "goal", team: "away", player: "own goal", minute: 23, assist: "bobby" },
                { type: "goal", team: "away", player: "titus", minute: 39, assist: "swan" },

                { type: "goal", team: "home", player: "nino", minute: 10 },
                { type: "goal", team: "home", player: "nino", minute: 20, assist: "edward" },
                { type: "yellow", team: "home", player: "nino", minute: 25 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "azul",
            awayTeamId: "hennessy",
            score: "1 : 1",
            week: 3,
            type: "league",
            date: "2025-08-21",
            time: "21:00",
            venue: "Lapangan B",
            events: [
                { type: "goal", team: "away", player: "awen", minute: 35 },
                { type: "goal", team: "home", player: "yongky", minute: 25, assist: "ali" },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "glenfiddich",
            awayTeamId: "macallan",
            score: "1 : 3",
            week: 3,
            type: "league",
            date: "2025-08-21",
            time: "21:00",
            venue: "Lapangan C",
            events: [
                { type: "goal", team: "away", player: "henry", minute: 35, assist: "raynaldo" },
                { type: "goal", team: "away", player: "herwin", minute: 25 },
                { type: "goal", team: "away", player: "herwin", minute: 29, assist: "budju" },

                { type: "goal", team: "home", player: "desmond", minute: 34, assist: "gil" },
            ] as MatchEvent[],
        },

        //week4
        {
            homeTeamId: "azul",
            awayTeamId: "macallan",
            score: "0",
            week: 4,
            type: "league",
            date: "2025-08-28",
            time: "20:00",
            venue: "Lapangan B",
            events: [
                // { type: "goal", team: "home", player: "bruno", minute: 23 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "hibiki",
            awayTeamId: "hennessy",
            score: "0",
            week: 4,
            type: "league",
            date: "2025-08-28",
            time: "20:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "glenfiddich",
            awayTeamId: "cockburn",
            score: "0",
            week: 4,
            type: "league",
            date: "2025-08-28",
            time: "21:00",
            venue: "Lapangan B",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "blacklabel",
            awayTeamId: "singleton",
            score: "0",
            week: 4,
            type: "league",
            date: "2025-08-28",
            time: "21:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },

        //cup2
        {
            homeTeamId: "blacklabel",
            awayTeamId: "azul",
            score: "0",
            week: 2,
            type: "cup",
            date: "2025-09-4",
            time: "20:00",
            venue: "Lapangan B",
            events: [
                // { type: "goal", team: "home", player: "bruno", minute: 23 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "glenfiddich",
            awayTeamId: "hibiki",
            score: "0",
            week: 2,
            type: "cup",
            date: "2025-09-4",
            time: "20:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "macallan",
            awayTeamId: "singleton",
            score: "0",
            week: 2,
            type: "cup",
            date: "2025-09-4",
            time: "21:00",
            venue: "Lapangan B",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "hennessy",
            awayTeamId: "cockburn",
            score: "0",
            week: 2,
            type: "cup",
            date: "2025-09-4",
            time: "21:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },

        //week5
        {
            homeTeamId: "blacklabel",
            awayTeamId: "hennessy",
            score: "0",
            week: 5,
            type: "league",
            date: "2025-09-11",
            time: "20:00",
            venue: "Lapangan B",
            events: [
                // { type: "goal", team: "home", player: "bruno", minute: 23 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "singleton",
            awayTeamId: "glenfiddich",
            score: "0",
            week: 5,
            type: "league",
            date: "2025-09-11",
            time: "20:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "hibiki",
            awayTeamId: "macallan",
            score: "0",
            week: 5,
            type: "league",
            date: "2025-09-11",
            time: "21:00",
            venue: "Lapangan B",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "azul",
            awayTeamId: "cockburn",
            score: "0",
            week: 5,
            type: "league",
            date: "2025-09-11",
            time: "21:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },

        //week6
        {
            homeTeamId: "hibiki",
            awayTeamId: "cockburn",
            score: "0",
            week: 6,
            type: "league",
            date: "2025-09-18",
            time: "20:00",
            venue: "Lapangan B",
            events: [
                // { type: "goal", team: "home", player: "bruno", minute: 23 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "blacklabel",
            awayTeamId: "macallan",
            score: "0",
            week: 6,
            type: "league",
            date: "2025-09-18",
            time: "20:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "singleton",
            awayTeamId: "azul",
            score: "0",
            week: 6,
            type: "league",
            date: "2025-09-18",
            time: "21:00",
            venue: "Lapangan B",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "glenfiddich",
            awayTeamId: "hennessy",
            score: "0",
            week: 6,
            type: "league",
            date: "2025-09-18",
            time: "21:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },

        //cup3
        {
            homeTeamId: "blacklabel",
            awayTeamId: "glenfiddich",
            score: "0",
            week: 3,
            type: "cup",
            date: "2025-09-25",
            time: "20:00",
            venue: "Lapangan B",
            events: [
                // { type: "goal", team: "home", player: "bruno", minute: 23 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "hibiki",
            awayTeamId: "azul",
            score: "0",
            week: 3,
            type: "cup",
            date: "2025-09-25",
            time: "20:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "macallan",
            awayTeamId: "hennessy",
            score: "0",
            week: 3,
            type: "cup",
            date: "2025-09-25",
            time: "21:00",
            venue: "Lapangan B",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "singleton",
            awayTeamId: "cockburn",
            score: "0",
            week: 3,
            type: "cup",
            date: "2025-09-25",
            time: "21:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },

        //week7
        {
            homeTeamId: "azul",
            awayTeamId: "glenfiddich",
            score: "0",
            week: 7,
            type: "league",
            date: "2025-10-2",
            time: "20:00",
            venue: "Lapangan B",
            events: [
                // { type: "goal", team: "home", player: "bruno", minute: 23 },
            ] as MatchEvent[],
        },
        {
            homeTeamId: "singleton",
            awayTeamId: "cockburn",
            score: "0",
            week: 7,
            type: "league",
            date: "2025-10-2",
            time: "20:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "macallan",
            awayTeamId: "hennessy",
            score: "0",
            week: 7,
            type: "league",
            date: "2025-10-2",
            time: "21:00",
            venue: "Lapangan B",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
        {
            homeTeamId: "blacklabel",
            awayTeamId: "hibiki",
            score: "0",
            week: 7,
            type: "league",
            date: "2025-10-2",
            time: "21:00",
            venue: "Lapangan C",
            events: [
                // { type: "yellow", team: "away", player: "Marc G", minute: 62 },
            ],
        },
    ]

type MatchEvent = {
    assist: string
    playerId: any
    type: "goal" | "assist" | "yellow" | "red"
    team: "home" | "away"
    player: string
    minute: number
}
